#+BLOG: wordpress
#+POSTID: 5
#+DATE: [2014-07-17 Thu 23:21]
#+CATEGORY: English
-----------------------
#+TITLE: Casablanca
-----------------------
#+BEGIN_VERSE
Rick: *Here's looking at you kid*. 
Llsa: : I wish I didn't love you so much. 
Rick: Inside we both know that you belong to Victor. You're part of his work and *the thing keeps him going*.  When the plane leaves the ground and you are not with him, you will regret it. Maybe not today, maybe not  tomorrow, but soon, for the rest of your life.
Llsa: What about us? 
Rick: We'll always have Paris. We didn't have it. We'd lost it until you came to Casablanca. We got it back last night. 
Llsa: When I said I would never leave you. 
Rick: And you never will.  I have a job to do too. Where I am going, you cannot follow. What I got to do, you cannot be any part of. IIls, I am not going be noble. But It doesn't take much to see the problems of three little people don't *amount to a hill of beans* in this crazy world.  Someday you will understand that. 
Rick: "Here's looking at you kid* 

M: Roundup the usual suspects.
Rick: I think this is a beginning of a beautiful friendship. 
#+END_VERSE

