#+BLOG: wordpress
#+POSTID: 12
#+DATE: [2014-07-19 Sat 12:49]
#+CATEGORY: English
#+TITLE: Meet Joe Black

#+BEGIN_VERSE
M: That's the way it is with men and women, isn't it. 
W: What's the way? 
M: *Nothing* lasts. 
W: I agree. 
M: Why? 
M: I am interested. 
W: I was just trying to be agreeable.

M:  If I need a doctor, you could be it. 
W: Yes, I could be her. 
M: This is my lucky day. I just get in the big, bad city. Not only do I find a doctor but a beautiful woman as well. 
M:  Do you mind me saying that. 
W: Oh no, of course. No, it's fine. It's fine, it's just...
M: (chuckling). Listen, could I buy you a cup of coffee? 
W: I have some patients coming in, so I should probably get going..
M: Yeah, yeah, I gotta get to the apartment and get off to work. 
W: Yeah. 
M: But I'd still like to have another cup of coffee. 
W: Um--
M: Would you let me do that? 
W: Well, yeah, okay. 
M: Deal. 

W: I've gotta to go. 
M: Listen. Did I say something wrong. 
W: No. No. It was, it was so right, it scares me. 
M: You know, I was thinking I don't want you to be my doctor. I don't want you to examine me. 
W: Why? 
M: Because I like you so much. 
W: I don't want to examine you. 
M: Why? 
W: Because  I like you so much. 
W:  Oh, boy. Oh. Now I gotta to go. 
M: Yep, Understood. Fair enough. See ya. 



Bill: Cause if you haven't tried, you haven't lived. 

M: Talk to me. 
D: There's gonna to be plenty time of that. 


M: I don't think they are *Ordinary*. I think they are great. I love keychain. 

Bill: I said, anyone here?
Joe: *Quiet* down.

Bill: What's this? Is this a joke? Some kind of *elaborate practical joke*?

Joe: The great Parrish *at a loss for words*.  The man from whose lips fall "rapture" and "passion" and "obsession". All those *admonitions*  about being *deliriously* happy, and there is no sense living your life without. All the *sparks* and energy you *give off* , the rosy advice you *dispense* in round pear-shaped tones.
Bill: Who are you? 
Joe: Just think of millenniums myltiplied by *eons* *compounded* by the time without end.  I've been around that long. But it's only recently that your *affairs* here have *piqued* my interest(similar use: pique my curiosity).Call it *boredom*. The natural curiosity of me, the most lasting and significant element in *existence*, has come to see you.  

Joe: The question that is in the back of you throat, choking the blood to your brain. ringing in your ears over and over again as you put it yourself. 

Joe: Joe sounds like a ringer, Bill. 

Susan: What are you doing her? 
Susan Cat got your tongue.  You wasn't so silent this morning. 
Joe: I was quite myself. 
Susan It's a shame that whoever you were couldn't be here tonight. 



Joe: Do you like Drew? 
Susan: Excuse me? 
Joe: When you put your mouth to his, it seems a *frequent* thing.
Susan: Drew is none of your business and neither is where I put my mouth.  
Joe: I am sorry. Do you live here? 
Susan: No, I don't live here. I am swimming here and now I am going home. 
Joe: Yes, What I am trying to say is that I would like it if we were friends. 
Susan: I've got plenty of friend. 
Joe: I don't have any. 
Susan: Well, I can see why. 
Joe: I didn't mean to offend you at dinner. But sometimes I am not quite at home around people. I get busy doing, uh, what it is I do. I don't seem to have developed..
Susan: Yes? 
Joe: I have *a certain* function to *perform* and it seems to take up most of my time. But sometimes I .. *speculate*.. that I haven't *left* room for anything else.
Susan: Hmm. I am sorry to say I know what you mean. 
Susan: Good night, Joe. 
Joe: Good night to you, Susan. 


M: I have this weak fealing in my knee...
W: And is your heart beating strangely?
M: Yes, faster.  The taste of your lips and the touch of your tongue that was wonderful

(after Making love)
W: What do we do now?
M: It'll come to us. 

Bill: What's going on, mm. I saw you kiss Susan. 
Joe: Yes, I saw you see me. 
Bill: You are at the wrong place, at the wrong time with the wrong woman. 
Joe: I'll be the judge of that.
Bill: I am her father.  
Joe: With all due respect,Bill. I am not asking your permission. 
Bill: You goddamn well should! 
Bill: You walk into my life. You give me the worse news a guy can get. You are dancing on the heads of pins of my business, my family. Now you're spooning with my daughter.
Joe: "Spooning"?
Bill: Yes. Stop repeating everything I said and turning it into a question. Spooning, fooling around. God knows what. Oh, you arrive on the scene--. Why your picked me? I still don't understand. 
Joe: I choose you for your *verve*,your excellence and your ability to instruct. You've lived a first rate life and I find it *eminently* usable. 
#+END_VERSE





