#+BLOG: wordpress
#+POSTID: 60
-----------------------
#+TITLE: Linux Utility Programs
#+DATE: <2014-08-13 Wed> 
#+CATEGORY: Scripting
-----------------------
This article means to summary some commonly utility programs I uses on a daily basis. The utility programs in this post often have different variants(BSD, GNU, POSIX, ect [fn:1]). 
* Piping
+ Piping with stdin redirection. Without the stdin redirection, emacs complains the stdin is not tty. 
  #+BEGIN_SRC shell
  ls prod_JP*|xargs zsh -c 'emacs "$@"</dev/tty'
  #+END_SRC
* find (Cf. [fn:2]):
+ -exec 
  #+BEGIN_SRC shell
    #The following commands do the same things: 
    find / -name core -exec /bin/rm -f '{}' \;
    find / -name core -exec /bin/rm -f '{}' +
    find / -name core | xargs /bin/rm -f
  #+END_SRC
    - The ‑exec is followed by some shell command line, ended with a semicolon (“;”). (The semicolon must be quoted from the shell, so find can see it!)  Within that command line, the word “{}” will expand out to the name of the found file. An alternate form of ‑exec ends with a plus-sign, not a semi-colon.  This form collects the filenames into groups or sets, and runs the command once per set.  (This is exactly what xargs does, to prevent argument lists from becoming too long for the system to handle.)[fn:2]
    + To handle exotic filenames(which contain spaces or newlines), use the form "find .. -print0|xargs -0 ..."

+ Gotcha: When no action is given, "-print" is assumed and grouping is perform. This could messed up the boolean operation precedence and give surprising results. See [fn:2].  
* tar
+ Archive and gzip a whole directory:  
#+BEGIN_SRC shell
  tar czvf ShiyuanGu.tar.gz ShiyuanGu  
#+END_SRC
+ Extract and uncompress: 
#+BEGIN_SRC shell
  tar xzvf ShiyuanGu.tar.gz ShiyuanGu  
#+END_SRC
* Footnotes

[fn:1] [[http://en.wikipedia.org/wiki/POSIX][WIKI-POSIX]]

[fn:2] [[http://content.hccfl.edu/pollock/unix/findcmd.htm][A Unix/Linux find command Tutorial]]


 
