* Stata 
** Getting Help
+ help summarize
+ search summarize
+ db summarize
+ `which logisitic`: show the source location of an ado command. For an ado command,
+ A quick look at the dataset: 
  - desc,d (d for detail) 
  - summarize, 
** Environment 
#+BEGIN_SRC stata
//save history along with output
. log using ".SHistory", append text
//list the 50 most recent command 
. #review 50 
#+END_SRC

** Exploratory Analysis
#+BEGIN_SRC stata
. use /b/data/BuyBoxWinner_1_147_all.dta, clear
. desc, fullname

Contains data from /b/data/BuyBoxWinner_1_147_all.dta
  obs:     1,670,108                          
 vars:            64                          21 Oct 2014 23:52
 size:   721,486,656                          
------------------------------------------------------------------------------------------------------------------------
              storage   display    value
variable name   type    format     label      variable label
------------------------------------------------------------------------------------------------------------------------
marketplace_id  byte    %8.0g                 
asin            str10   %10s                  
gl_product_gr~p int     %8.0g          
. sample 10
. summ landedPrice if (priceBandToUse == 1) ,d
. list in 1/10
. tab A1 A2, row col //tabulate two ways.  
#+END_SRC
** Importing/Exporting
#+BEGIN_SRC stata
// save the final input data into stata format
. compress
. save "${dataFolder}/data/${dataPrefix}_`MarketplaceID'_`GL'_all.dta" , replace
. saveold "${dataFolder}/data/${dataPrefix}_`MarketplaceID'_`GL'_all_stata12.dta" , replace//for stata12 

// save csv 
. outsheet marketplace_id asin gl_product_group dummy_fast_track dummy_fba dummy_prime dummy_amazon dummy_buybox_win dummy_purchase landedPrice hit_day dummy_win dummy_mfn dummy_afn aid_day priceBandToUse seller_rating is_prime_offer using /b/data/BuyBoxWinner_1_147_small.csv , comma
. insheet using /b/data/BuyBoxWinner_1_147_small.csv, clear
(18 vars, 1670108 obs)
#+END_SRC
* R
** Getting Help
+ help(func)
+ getAnywhere(obj) 
+ help("[[")
+ help.start(): 
This will launch a Web browser that allows the help pages to be browsed with hyperlinks(it only uses localhost: http://127.0.0.1:21389/doc/html/Search.html).This link Search Engine & Keywords is particularly useful. We can also use the internet link http://stat.ethz.ch/R-manual/R-devel/doc/html/. The local host and the internet link should be the same. 
+ help.search() (alternative ??, eg, ??solve) 
** Environment
R saves the workplace object to the current directory .RData and the command history to .Rhistroy 
*** Change #col to display
The default width is 80 characters. We can change it to 160 characters by
#+BEGIN_SRC R
> options(width=160)
#+END_SRC
*** show environment 
#+BEGIN_SRC r
> options() #list all options
> ls() #list all objects
> objects() #remove objects in the workspace
#+END_SRC
*** attach/detach dataframe: 
attach()/detach() will add a dataframe to the search path. 
#+BEGIN_SRC R
> search()
[1] ".GlobalEnv"        "package:stats"     "package:graphics"  "package:grDevices" "package:utils"     "package:datasets"  "package:methods"  
[8] "Autoloads"         "package:base"     
> attach(ds)
> search()
 [1] ".GlobalEnv"        "ds"                "package:stats"     "package:graphics"  "package:grDevices" "package:utils"     "package:datasets" 
 [8] "package:methods"   "Autoloads"         "package:base"     
> detach(ds)
> search()
[1] ".GlobalEnv"        "package:stats"     "package:graphics"  "package:grDevices" "package:utils"     "package:datasets"  "package:methods"  
[8] "Autoloads"         "package:base"   
#+END_SRC
*** history
#+BEGIN_SRC R
  history(max.show=Inf)
#+END_SRC
*** Executing Commands: 
   #+BEGIN_SRC R 
      ## execute a script 
      source("commands.R")
      ## Redirecting output
      sink("record.lis")
   #+END_SRC
   
** Data Type
*** vector 
**** find indices
#+BEGIN_SRC R
  which(ds.filter[,"ToUse"] %in% c(2)) ##find the row indices where the column "ToUse" equals to 2
#+END_SRC
*** Factor 
#+BEGIN_SRC R
##Drop level after subsetting, say subds is obtained by subsetting, and some levels in subds$F are of zero counts after subsetting
subds$F=factor(subds$F)
#+END_SRC
** Data Analysis 
*** Summary of data
#+BEGIN_SRC R
ds <- read.csv("/workplace/shiyuang/b/data/BuyBoxWinner_1_147_small.csv", header=T)
names(ds)
summary(ds)
head(ds, 5)
str(ds)  #show structure
ds[1:3,]
cor(ds) #won't work if ds has factors. 
corrplot.mix(cor(ds)) #visualize cor; library(corrplot)

#quantile analysis 
# right=T use left closed and right open interval, [a,b), include.lowest indicates whether the end point is included. 
ds$QRev <- cut(ds$total_tkt_rev_yr1,breaks = quantile(ds$total_tkt_rev_yr1),include.lowest = TRUE,right=TRUE) 
#+END_SRC
*** Extracting rows/columns
#+BEGIN_SRC r
dim(ds[ds$dummy_win == 0,])
ds.top[ds.top$asin=="B003ES5ZSW",!(names(ds.top) %in% c("count","sum_dummy_win")) #excluding cols 
#+END_SRC
*** Combining rows/columns
#+BEGIN_SRC R
cbind(ds1,ds2)
cbind(v1,X=v2) #combine columns, appending "X" to the v2's columns' name)
#+END_SRC
*** Grouping 
#+BEGIN_SRC R
# The following calculates the the number of observations for each pair (priceBand, sample_rate)    
aggregate(data=ds, j~priceBand+sample_rate, FUN=length) 
#+END_SRC
Cf. dplyr package for more sophisticated grouping
** Plotting
*** simple boxplot/export
#+BEGIN_SRC r 
with(subds, plot(as.numeric(is_prime_offer), landedPrice, col=dummy_win, pch=as.numeric(dummy_win)))
boxplot(data=subds, pPO~sample_rate)
title("My Title")
dev.copy(png, "~/tmp/tmp.png") #export the graph; plot first then run this; otherwise, error of null device
dev.off() #save the graph ; otherwise, error of file format. 
#+END_SRC
*** combining plots/zoom in
#+BEGIN_SRC R
p <- ggplot()+geom_density(aes(x=offer_price),na.rm=TRUE)+coord_cartesian(xlim=c(10,2000))+facet_grid
#+END_SRC
#+BEGIN_SRC R
p <- ggplot()+geom_density(data=ds.retail.trig[t1==0,],aes(x=offer_price),na.rm=TRUE,color="blue")+coord_cartesian(xlim=c(10,2000))+geom_density(data=ds.retail.trig[t1==1,],aes(x=offer_price),na.rm=TRUE,color="red")+coord_cartesian(xlim=c(10,2000))
#+END_SRC
#+BEGIN_SRC R
attach(mtcars)
par(mfrow=c(2,2))
plot(wt,mpg, main="Scatterplot of wt vs. mpg")
plot(wt,disp, main="Scatterplot of wt vs disp")
hist(wt, main="Histogram of wt")
boxplot(wt, main="Boxplot of wt")
#+END_SRC
*** Multiple line plot based on factors
#+BEGIN_SRC R
###The following plot a line for each ds$type using different colors
ggplot(ds, aes(x=time, y=val, colour=type))+geom_line()+scale_x_continuous(breaks=seq(1,12,1))+xlab("Month")+ylab("Median gts13 score")

#+END_SRC
*** multi-boxplot
#+BEGIN_SRC R
  library(ggplot2)
  library(grid)
  # Multiple plot function
  # This function is taken from Cookbook for R
  # ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
  # - cols:   Number of columns in layout
  # - layout: A matrix specifying the layout. If present, 'cols' is ignored.
  #
  # If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
  # then plot 1 will go in the upper left, 2 will go in the upper right, and
  # 3 will go all the way across the bottom.
  #
  multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
    require(grid)

    # Make a list from the ... arguments and plotlist
    plots <- c(list(...), plotlist)

    numPlots = length(plots)

    # If layout is NULL, then use 'cols' to determine layout
    if (is.null(layout)) {
      # Make the panel
      # ncol: Number of columns of plots
      # nrow: Number of rows needed, calculated from # of cols
      layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                      ncol = cols, nrow = ceiling(numPlots/cols))
    }

   if (numPlots==1) {
      print(plots[[1]])

    } else {
      # Set up the page
      grid.newpage()
      pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

      # Make each plot, in the correct location
      for (i in 1:numPlots) {
        # Get the i,j matrix positions of the regions that contain this subplot
        matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

        print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
             layout.pos.col = matchidx$col))
      }
    }
  }

  # plotting
  ds<-read.csv(file="/Users/shiyuang/tmp/20141222/stata-estimates.csv", header=T)
  ds$priceBand <- as.factor(ds$priceBand)
  ds$sample_rate <- as.factor(ds$sample_rate)
  ds$pPO <- - ds$bPO/ds$a
  #ds$pSR <- - ds$bSR/ds$a
  ds$pFT <- - ds$bFT/ds$a
  for (i in seq(0, 11, by=1)){
      subds<-ds[ds$priceBand==i,]
      a <- ggplot(data=subds)+geom_boxplot(aes(x=sample_rate,y=a))+ggtitle("Price Coeff.")
      gpPO <- ggplot(data=subds)+geom_boxplot(aes(x=sample_rate,y=pPO))+ggtitle("Premia PO")
      #gpSR <- ggplot(data=subds)+geom_boxplot(aes(x=sample_rate,y=pSR))+ggtitle("Premia SR")
      gpFT <- ggplot(data=subds)+geom_boxplot(aes(x=sample_rate,y=pFT))+ggtitle("Premia FT")
      #multiplot(a,gpPO,gpSR,gpFT,cols=4)
      multiplot(a,gpPO,gpFT,cols=3)
      dev.copy(png, paste(paste("~/tmp/20141222/pb",i,sep="_"),"png",sep="."),width=1280,height=480)
      dev.off()
  }
#+END_SRC
	
*** Color Scheme: 
checkout RColorBrewer(RColorBrewer::display.brewer.all() show all color palettes. 
*** gglot2
+ *plot* = a set of layers + scales + Coordinates + Facets 
+ *Layer* = data + aes(visual properties, like x(horizontal position), y(vertical positions), fill  ) + geom + stat transform(bins in histogram) + position adjustment 
+ *Data*: what to visualize; each aesthetic must be a column(transform the table to long format); In gglot terminology, categorical variables are called /discrete/, numerical variables are called /continuous/. This is different than standard R terminology. Only a certain data type might make sense for a particular type of graph. 
+ *Aesthetic*: visual properties, such as horizon position (x=..), vertical position(y=..), fill=.. 
+ *Scale* controls the mapping from the values to aesthetic space. functions setting the scale include: scale_x_continuous(limit=c(0,8)), scale_colour_manual();   
+ *Guides* map the visual properties back to data space and guides the viewer to interpret the graph (eg. Tick marks, axis labels) 
+ *Stats* transforms the data before it is mapped to aesthetic. For example, /geom_histogram(..)/ counts for each bin are then used to specify the height of a bar. 
+ *Themes* specifies the aspects of graph's appearance fall outside the scope of the /grammar of graphics/(Leland Willkinson), like background color, graphing area, fonts, grid lines, title text. This is  set by the function /theme()/ 
*** rgl
Use RStudio. X-window gives strangle colors and interactive behaviors.
#+BEGIN_SRC R
rm(list=ls(all.names=TRUE))
library(rgl)
##Necessary data transform  omitted here 
color.z<-hsv(r,1.0,1.0,alpha=t.n) # t.n is in [0,1]; 0 for completely transparent. 
open3d()
plot3d(x,y,z,col=color.z, alpha=t.n, xlab="", ylab="", zlab="",axes=FALSE)
axes3d(edges =c("x--","y--","z--"),nticks = 4,cex=0.5)
rgl.bbox(color="grey40",emission="grey50", xlen=0, ylen=0,zlen=0) #specify the appearance of the bounding box. 
#rgl.material(color="black") #reset to solid color for the text below
mtext3d("num. partners",edge="x--",color="black",line=3)
mtext3d("household income", edge="y--",color="black",line=4)
mtext3d("ticket revenue", edge="z--",color="black",line=4)
#interactively change the orientation and then get the view by  http://stackoverflow.com/questions/16362381/save-the-orientation-of-a-rgl-plot3d-plot
myview<-structure(c(0.851206958293915, -0.249241456389427, -0.461872220039368, 
                     0, -0.457670271396637, -0.783240020275116, -0.420800983905792, 
                     0, -0.256875574588776, 0.569573879241943, -0.780768990516663, 
                     0, 0, 0, 0, 1), .Dim = c(4L, 4L)) #specify the transformation matrices. 
par3d(userMatrix=myview)
rgl.snapshot("tmp.png",fmt="png") 
#+END_SRC
** dplyr:A Grammar of Data Manipulation 
#+BEGIN_SRC R
library(dplyr)
options(dplyr.print_max = 1e9) # so that it prints all rows of tbl_df;sadly, there seems no easy way to print all columns. please cast  data.frame for printing all rows and columns: as.data.frame(ds.top)  
ds.top<-merge(ds, ds.aid, by="aid_day") #inner join
ds.top %>% group_by(asin) %>% summarise(count=n(),total_bb=sum(dummy_win)) %>% arrange(-count) %>% head(10)
unique(ds.top[ds.top$asin=="B003ES5ZSW",!(names(ds.top) %in% c("count","sum_dummy_win"))]) %>% head(5) 
#Note:
arrange(ds, desc(total_bb)) #sort
#+END_SRC
** Simple linear regression
#+BEGIN_SRC r
> mymodel = lm(y~x, ds)
> summary(mymodel)
> confint(mymodel, level=0.95)
#+END_SRC
** Mixed/Fixed effect, lfe/lme4
#+BEGIN_SRC R
## from library(lfe), analogue to Stata:areg
m1<-felm(dummy_win ~ landedPrice+is_prime_offer+dummy_fast_track|aid_day, data=ds.train)

library(lme4)
hdp <- read.csv("http://www.ats.ucla.edu/stat/data/hdp.csv")
hdp <- within(hdp, {
  Married <- factor(Married, levels = 0:1, labels = c("no", "yes"))
  DID <- factor(DID)
  HID <- factor(HID)
})
(fm1 <- lmer(Reaction ~ Days+ (Days| Subject), sleepstudy)) # Same as (fm1 <- lmer(Reaction ~ Days + 1 + (Days+1| Subject), sleepstudy))

(fm2 <- lmer(Reaction ~ Days+ (1| Subject), sleepstudy)) #consider the random effect only on intercept, not on Days' coeff. 
(fm3 <- lmer(Reaction ~ Days + (Days +1 ||Subject), sleepstudy)) ## || indicate no interaction between Days and intercept; Alternatively, the formula (Days+1||Subject), can also be writtern as  Reaction ~ Days + ((1 | Subject) + (0 + Days | Subject)) (ref summary(fm1))
fm3 <- glmer(remission ~ IL6 + CRP + CancerStage + LengthofStay + Experience +
    (1 | DID), data = hdp, family = binomial, control = glmerControl(optimizer = "bobyqa"),
    nAGQ = 10)
print(m, corr = FALSE)
fixef(m)
#+END_SRC 
** Advanced R
*** Construct Syntax on the Fly
#+BEGIN_SRC R
> targetName <- "OneFactorScore"
> eval(substitute(y.test <- ds.test$targetName,list(targetName=targetName)))
#+END_SRC
*** deparse: turn unevaluated expression into string
#+BEGIN_SRC R
< deparse(args(lm))

#+END_SRC

*** Constructing Formulae
#+BEGIN_SRC r
#y ~ the first ten columns of datafram ds
lr.formula <- reformulate(names(ds)[1:10], “y”)  
glm.fit <- glm(lr.formula, data=ds, family=binomial)

#+END_SRC
*** extraction from a model 
#+BEGIN_SRC R
  lms <- regsubsets(target-var~., data=ds.pm,nv=30, method="forward")
  model.id <- 1
  lm.id <- lm(reformulate(names(coef(lms, model.id))[-1],"target-var") # -1: no need to include the intercept in names. 
#+end_src

	
